version: '2'

services:

  php:
    build: .
    volumes: ['./:/app']

  composer:
    extends: { service: php }
    entrypoint: ['composer']

  behat:
    extends: { service: php }
    entrypoint: ['./behat.sh']
    links: ['selenium', 'novnc']

  selenium:
    image: selenium/standalone-chrome-debug:3.11.0-californium
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1440 #1360 #1200 #900
      - SCREEN_HEIGHT=900 #768 #675
    ports:
      - 4444:4444
      - 5900:5900

  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5900
    ports:
      - 8081:8081
    links:
      - selenium
